# Generated by Django 3.2.9 on 2022-01-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aphood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile.jpg', upload_to='photos/'),
        ),
    ]
